import SEOHead from "@/components/SEOHead";

const TermsPage = () => (
  <>
    <SEOHead title="Terms & Conditions" description="Read the Terms and Conditions for Free AI Tools Hub. Understand the rules and guidelines for using our free AI tools." />
    <div className="container py-12 max-w-3xl">
      <h1 className="text-4xl font-bold mb-6">Terms & Conditions</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: March 14, 2025</p>
      <div className="space-y-4 text-muted-foreground leading-relaxed">
        <h2 className="text-xl font-bold text-foreground">1. Acceptance of Terms</h2>
        <p>By accessing and using Free AI Tools Hub, you agree to be bound by these terms and conditions.</p>
        <h2 className="text-xl font-bold text-foreground">2. Use of Services</h2>
        <p>Our tools are provided free of charge for personal and commercial use. You may use the generated content for any lawful purpose.</p>
        <h2 className="text-xl font-bold text-foreground">3. Content Disclaimer</h2>
        <p>The content generated by our tools is created using algorithms and templates. We do not guarantee the accuracy, uniqueness, or suitability of generated content. Users are responsible for reviewing and modifying generated content before use.</p>
        <h2 className="text-xl font-bold text-foreground">4. Intellectual Property</h2>
        <p>The website design, code, and branding are the property of Free AI Tools Hub. Content generated using our tools belongs to the user.</p>
        <h2 className="text-xl font-bold text-foreground">5. Limitation of Liability</h2>
        <p>Free AI Tools Hub is provided "as is" without any warranties. We are not liable for any damages arising from the use of our tools or website.</p>
        <h2 className="text-xl font-bold text-foreground">6. Modifications</h2>
        <p>We reserve the right to modify these terms at any time. Continued use of the website constitutes acceptance of updated terms.</p>
        <h2 className="text-xl font-bold text-foreground">7. Contact</h2>
        <p>For questions about these terms, please <a href="/contact" className="text-primary hover:underline">contact us</a>.</p>
      </div>
    </div>
  </>
);

export default TermsPage;
